name: Run hourly job and push changes

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0 UTC
  workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python autocal.py  # Replace with your actual script

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Hourly update [auto]" || echo "No changes to commit"
          git push
